# Generated by Django 4.2 on 2025-04-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_text',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='responseoption',
            name='text_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='responseoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sondage.option'),
        ),
    ]
