# Generated by Django 4.2 on 2025-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondage', '0002_question_is_text_responseoption_text_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='likert_value',
        ),
        migrations.AddField(
            model_name='responseoption',
            name='likert_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
